const String wilayasJson = '''
{
  "Wilayas": [
    {"id": 1, "name": "Adrar", "communes": ["Aoulef", "Akabli", "Adrar"]},
    {"id": 2, "name": "Chlef", "communes": ["Chlef", "Ouled Fares", "El Karimia"]},
    {"id": 3, "name": "Laghouat", "communes": ["Laghouat", "Ksar El Hirane", "Aflou"]},
    {"id": 4, "name": "Oum El Bouaghi", "communes": ["Ain Beida", "Oum El Bouaghi", "Ain M'Lila"]},
    {"id": 5, "name": "Batna", "communes": ["Batna", "Barika", "Merouana"]},
    {"id": 6, "name": "Béjaïa", "communes": ["Béjaïa", "Amizour", "Barbacha"]},
    {"id": 7, "name": "Biskra", "communes": ["Biskra", "Ouled Djellal", "Tolga"]},
    {"id": 8, "name": "Béchar", "communes": ["Béchar", "Beni Abbes", "Kénadsa"]},
    {"id": 9, "name": "Blida", "communes": ["Blida", "Boufarik", "El Affroun"]},
    {"id": 10, "name": "Bouira", "communes": ["Bouira", "Lakhdaria", "Sour El Ghozlane"]},
    {"id": 11, "name": "Tamanrasset", "communes": ["Tamanrasset", "Ain Salah", "In Guezzam"]},
    {"id": 12, "name": "Tébessa", "communes": ["Tébessa", "El Aouinet", "Bir el Ater"]},
    {"id": 13, "name": "Tlemcen", "communes": ["Tlemcen", "Nedroma", "Ghazaouet"]},
    {"id": 14, "name": "Tiaret", "communes": ["Tiaret", "Frenda", "Sougueur"]},
    {"id": 15, "name": "Tizi Ouzou", "communes": ["Tizi Ouzou", "Azeffoun", "Benni Yenni"]},
    {"id": 16, "name": "Alger", "communes": ["Alger Centre", "Bab El Oued", "El Madania"]},
    {"id": 17, "name": "Djelfa", "communes": ["Djelfa", "Hassi Bahbah", "Ain Oussera"]},
    {"id": 18, "name": "Jijel", "communes": ["Jijel", "El Aouana", "Ziama Mansouriah"]},
    {"id": 19, "name": "Sétif", "communes": ["Sétif", "El Eulma", "Ain Oulmene"]},
    {"id": 20, "name": "Saïda", "communes": ["Saïda", "Ain El Hadjar", "Ouled Brahim"]},
    {"id": 21, "name": "Skikda", "communes": ["Skikda", "El Harrouch", "Azzaba"]},
    {"id": 22, "name": "Sidi Bel Abbès", "communes": ["Sidi Bel Abbès", "Sfisef", "Telagh"]},
    {"id": 23, "name": "Annaba", "communes": ["Annaba", "El Bouni", "Seraidi"]},
    {"id": 24, "name": "Guelma", "communes": ["Guelma", "Hammam Debagh", "Heliopolis"]},
    {"id": 25, "name": "Constantine", "communes": ["Constantine", "El Khroub", "Ain Smara"]},
    {"id": 26, "name": "Médéa", "communes": ["Médéa", "Ksar El Boukhari", "Berrouaghia"]},
    {"id": 27, "name": "Mostaganem", "communes": ["Mostaganem", "Ain Tedeles", "Sidi Ali"]},
    {"id": 28, "name": "M'Sila", "communes": ["M'Sila", "Bou Saada", "Ain El Melh"]},
    {"id": 29, "name": "Mascara", "communes": ["Mascara", "Sig", "Mohammadia"]},
    {"id": 30, "name": "Ouargla", "communes": ["Ouargla", "Hassi Messaoud", "Touggourt"]},
    {"id": 31, "name": "Oran", "communes": ["Oran", "Es Senia", "Bir El Djir"]},
    {"id": 32, "name": "El Bayadh", "communes": ["El Bayadh", "Brezina", "El Abiodh Sidi Cheikh"]},
    {"id": 33, "name": "Illizi", "communes": ["Illizi", "Djanet", "In Amenas"]},
    {"id": 34, "name": "Bordj Bou Arreridj", "communes": ["Bordj Bou Arreridj", "Bordj Zemoura", "El Hamadia"]},
    {"id": 35, "name": "Boumerdès", "communes": ["Boumerdès", "Boudouaou", "Khemis El Khechna"]},
    {"id": 36, "name": "El Tarf", "communes": ["El Tarf", "El Kala", "Bouteldja"]},
    {"id": 37, "name": "Tindouf", "communes": ["Tindouf", "Oum El Assel"]},
    {"id": 38, "name": "Tissemsilt", "communes": ["Tissemsilt", "Theniet El Had", "Bordj Bounaama"]},
    {"id": 39, "name": "El Oued", "communes": ["El Oued", "Guemar", "El M'Ghair"]},
    {"id": 40, "name": "Khenchela", "communes": ["Khenchela", "Kais", "El Hamma"]},
    {"id": 41, "name": "Souk Ahras", "communes": ["Souk Ahras", "Sedrata", "Taoura"]},
    {"id": 42, "name": "Tipaza", "communes": ["Tipaza", "Cherchell", "Hadjout"]},
    {"id": 43, "name": "Mila", "communes": ["Mila", "Chelghoum Laid", "Tadjenanet"]},
    {"id": 44, "name": "Aïn Defla", "communes": ["Aïn Defla", "Khémis Miliana", "El Abadia"]},
    {"id": 45, "name": "Naâma", "communes": ["Naâma", "Mécheria", "Aïn Sefra"]},
    {"id": 46, "name": "Aïn Témouchent", "communes": ["Aïn Témouchent", "Hammam Bou Hadjar", "Beni Saf"]},
    {"id": 47, "name": "Ghardaïa", "communes": ["Ghardaïa", "Metlili", "El Menia"]},
    {"id": 48, "name": "Relizane", "communes": ["Relizane", "Oued Rhiou", "Ammi Moussa"]},
    {"id": 49, "name": "El M'Ghair", "communes": ["El M'Ghair", "Djamaa", "Hassi Khalifa"]},
    {"id": 50, "name": "El Menia", "communes": ["El Menia", "Hassi Gara", "Menasra"]},
    {"id": 51, "name": "Ouled Djellal", "communes": ["Ouled Djellal", "Sidi Khaled", "Ras El Miad"]},
    {"id": 52, "name": "Bordj Baji Mokhtar", "communes": ["Bordj Baji Mokhtar", "Timiaouine"]},
    {"id": 53, "name": "Béni Abbès", "communes": ["Béni Abbès", "Tamtert", "Igli"]},
    {"id": 54, "name": "Timimoun", "communes": ["Timimoun", "Ouled Said", "Charouine"]},
    {"id": 55, "name": "Touggourt", "communes": ["Touggourt", "Tebesbest", "Nezla"]},
    {"id": 56, "name": "Djanet", "communes": ["Djanet", "Iherir"]},
    {"id": 57, "name": "In Salah", "communes": ["In Salah", "Foggaret Ezzoua"]},
    {"id": 58, "name": "In Guezzam", "communes": ["In Guezzam", "Ain Salah"]}
  ]
}
''';
