// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJ3sPGPbz5Cfd4bQwRBxb_8NXHjuUCNs',
    appId: '1:894656592896:web:292a45d7cfd4ab41ddace5',
    messagingSenderId: '894656592896',
    projectId: 'creno-ad53a',
    authDomain: 'creno-ad53a.firebaseapp.com',
    storageBucket: 'creno-ad53a.appspot.com',
    measurementId: 'G-5DEJMMN0V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8_v4D0DsFiZOd8dQz5da6fPNly2X7JY',
    appId: '1:894656592896:android:dafc2d71ec0e73edddace5',
    messagingSenderId: '894656592896',
    projectId: 'creno-ad53a',
    storageBucket: 'creno-ad53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnl7phBfuKF8wyorS7yTVtCLmWKyYkQ-w',
    appId: '1:894656592896:ios:1356ab1c92f0768eddace5',
    messagingSenderId: '894656592896',
    projectId: 'creno-ad53a',
    storageBucket: 'creno-ad53a.appspot.com',
    iosBundleId: 'com.example.pfeprojet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnl7phBfuKF8wyorS7yTVtCLmWKyYkQ-w',
    appId: '1:894656592896:ios:017c8d4ae1d9897dddace5',
    messagingSenderId: '894656592896',
    projectId: 'creno-ad53a',
    storageBucket: 'creno-ad53a.appspot.com',
    iosBundleId: 'com.example.pfeprojet.RunnerTests',
  );
}
